<a href="https://colab.research.google.com/github/Pestrdan/netology_research/blob/main/Machine_learning/FEML_28_HW2_%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8_%D0%BF%D0%BE%D1%82%D0%B5%D1%80%D1%8C_%D0%B8_%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Загрузите данные. Используйте датасет с ирисами. Его можно загрузить непосредственно из библиотеки Sklearn. В данных оставьте только 2 класса: Iris Versicolor, Iris Virginica.**

In [ ]:
from sklearn import datasets
from sklearn.metrics import accuracy_score

In [ ]:
iris = datasets.load_iris()

In [ ]:
X_pre = iris.data
y_pre = iris.target

In [ ]:
import numpy as np

In [ ]:
X1 = np.array([iris.data[0]])
n = 0
for i in y_pre:
  if i != 0:
    X1 = np.concatenate((X1, np.array([X_pre[n]])), axis=0)
  else:
    pass
  n += 1
X = X1[1:]
print(X[:5])

[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
X = StandardScaler().fit_transform(X)
print(X[:5])

[[ 1.11900931  0.99068792 -0.25077906 -0.65303909]
 [ 0.20924564  0.99068792 -0.49425387 -0.41643072]
 [ 0.96738203  0.68864892 -0.00730424 -0.41643072]
 [-1.15539985 -1.72766308 -1.10294091 -0.88964745]
 [ 0.36087292 -0.21746808 -0.37251647 -0.41643072]]


In [ ]:
y = np.array([])
for i in y_pre:
  if i == 1:
    y = np.append(y, 0)
  elif i == 2:
    y = np.append(y, 1)
  else:
    pass
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


# **2. Самостоятельно реализуйте логистическую регрессию, без использования метода LogisticRegression из библиотеки. Можете использовать библиотеки pandas, numpy, math для реализации. Оформите в виде функции. *Оформите в виде класса с методами.**

In [ ]:
#Добавляем константный признак для ускорение реализации
X = np.c_[np.ones(len(X)), X]
X

array([[ 1.        ,  1.11900931,  0.99068792, -0.25077906, -0.65303909],
       [ 1.        ,  0.20924564,  0.99068792, -0.49425387, -0.41643072],
       [ 1.        ,  0.96738203,  0.68864892, -0.00730424, -0.41643072],
       [ 1.        , -1.15539985, -1.72766308, -1.10294091, -0.88964745],
       [ 1.        ,  0.36087292, -0.21746808, -0.37251647, -0.41643072],
       [ 1.        , -0.8521453 , -0.21746808, -0.49425387, -0.88964745],
       [ 1.        ,  0.05761837,  1.29272692, -0.25077906, -0.17982236],
       [ 1.        , -2.06516352, -1.42562408, -1.95510276, -1.59947255],
       [ 1.        ,  0.5125002 ,  0.08457092, -0.37251647, -0.88964745],
       [ 1.        , -1.61028169, -0.51950708, -1.22467832, -0.65303909],
       [ 1.        , -1.91353624, -2.63378009, -1.71162795, -1.59947255],
       [ 1.        , -0.54889074,  0.38660992, -0.8594661 , -0.41643072],
       [ 1.        , -0.39726347, -2.02970209, -1.10294091, -1.59947255],
       [ 1.        , -0.24563619,  0.0

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def logloss(y, y_proba):
    logloss_1 = np.sum(np.log(y_proba[y == 1] + 1e-30))
    logloss_0 = np.sum(np.log(1 - y_proba[y == 0] + 1e-30))
    logloss_total = -(logloss_0 + logloss_1) / len(y)
    return logloss_total


def gr_logloss(X, W, y):
    y_proba = sigmoid(X @ W)
    grad = X.T @ (y_proba - y)
    return grad

In [ ]:
import pandas as pd
results = pd.DataFrame(columns=['Метод', 'Метрика', 'Итерация'])

# **3. Реализуйте метод градиентного спуска. Обучите логистическую регрессию этим методом. Выберете и посчитайте метрику качества. Метрика должна быть одинакова для всех пунктов домашнего задания. Для упрощения сравнения выберете только одну метрику.**

In [ ]:
%%time
# установка минимального значения, на которое должны изменяться веса
eps = 0.00001

# первоначальная точка
np.random.seed(43)
W = np.random.randn(X.shape[1])

# размер шага (learning rate)
learning_rate = 0.01

next_W = W

# количество итераций
n = 200
for i in range(n):
    cur_W = next_W

    # движение в негативную сторону вычисляемого градиента
    next_W = cur_W - learning_rate * gr_logloss(X, W, y)

    # остановка когда достигнута необходимая степень точности
    if np.linalg.norm(cur_W - next_W) <= eps:
        break

    #print(f"Итерация: {i+1}")
    # print(f"Текущая точка {cur_W}| Следующая точка {next_W}")
    y_proba = sigmoid(X @ next_W)
    y_class = np.where(y_proba >= 0.5, 1, 0)
    #accuracy = (y_class == y).sum() / len(y)
    accuracy = accuracy_score(y, y_class)
    #print(f"Logloss {logloss(y, y_proba)}")
    #print(f"Accuracy {accuracy}")
    #print("--------------------------------------------------------")
    results.loc[len(results.index)] = ['Gradient descent', accuracy, i+1]

CPU times: user 508 ms, sys: 2.18 ms, total: 510 ms
Wall time: 545 ms


In [ ]:
next_W

array([-11.2700489 ,  88.92247368,  55.16406852, 107.65152962,
        96.29013416])

In [ ]:
%%time
# установка минимального значения, на которое должны изменяться веса
eps = 0.00001

# первоначальная точка
np.random.seed(43)
W = np.random.randn(X.shape[1])

# размер шага (learning rate)
learning_rate = 0.01

next_W = W

#кол-во точек для Mini-Batch
amount = 10

# количество итераций
n = 200
for i in range(n):
    cur_W = next_W
    idx = np.random.choice(len(X), size=amount, replace=False)

    # движение в негативную сторону вычисляемого градиента
    next_W = cur_W - learning_rate * gr_logloss(X[idx], W, y[idx])

    # остановка когда достигнута необходимая степень точности
    if np.linalg.norm(cur_W - next_W) <= eps:
        break

    #print(f"Итерация: {i}")
    # print(f"Текущая точка {cur_W}| Следующая точка {next_W}")
    y_proba = sigmoid(X @ next_W)
    y_class = np.where(y_proba >= 0.5, 1, 0)
    accuracy = (y_class == y).sum() / len(y)
    #accuracy = accuracy_score(y, y_class)
    #print(f"Logloss {logloss(y, y_proba)}")
    #print(f"Accuracy {accuracy}")
    #print("--------------------------------------------------------")
    results.loc[len(results.index)] = ['Mini-Batch', accuracy, i+1]

CPU times: user 393 ms, sys: 2.2 ms, total: 396 ms
Wall time: 422 ms


# **4. Повторите п. 3 для метода скользящего среднего (Root Mean Square Propagation, RMSProp).**

In [ ]:
%%time
k = 200
lr = 0.01
eps_1 = 0.00001

# первоначальная точка
np.random.seed(43)
W = np.random.randn(X.shape[1])
weights_0, weights_1, weights_2, weights_3, weights_4, = [W[0]], [W[1]], [W[2]], [W[3]], [W[4]]

alphas = [0, 0, 0, 0, 0]
eps = 10e-7
rho = 0.9
amount = 10

for i in range(k):
    idx = np.random.choice(len(X), size=amount, replace=False)
    grad = gr_logloss(X[idx], W, y[idx])

    alphas[0] = rho * alphas[0] + (1 - rho) * grad[0] ** 2
    alphas[1] = rho * alphas[1] + (1 - rho) * grad[1] ** 2
    alphas[2] = rho * alphas[2] + (1 - rho) * grad[2] ** 2
    alphas[3] = rho * alphas[3] + (1 - rho) * grad[3] ** 2
    alphas[4] = rho * alphas[4] + (1 - rho) * grad[4] ** 2

    lr_k_0 = lr / np.sqrt(alphas[0] + eps)
    lr_k_1 = lr / np.sqrt(alphas[1] + eps)
    lr_k_2 = lr / np.sqrt(alphas[2] + eps)
    lr_k_3 = lr / np.sqrt(alphas[3] + eps)
    lr_k_4 = lr / np.sqrt(alphas[4] + eps)

    new_w_0 = weights_0[-1] - lr_k_0 * grad[0]
    new_w_1 = weights_1[-1] - lr_k_1 * grad[1]
    new_w_2 = weights_2[-1] - lr_k_2 * grad[1]
    new_w_3 = weights_3[-1] - lr_k_3 * grad[1]
    new_w_4 = weights_4[-1] - lr_k_4 * grad[1]

    weights_0.append(new_w_0)
    weights_1.append(new_w_1)
    weights_2.append(new_w_2)
    weights_3.append(new_w_3)
    weights_4.append(new_w_4)
    prev_W = np.array([weights_0[-2], weights_1[-2], weights_2[-2], weights_3[-2], weights_4[-2]])
    curent_W = np.array([weights_0[-1], weights_1[-1], weights_2[-1], weights_3[-1], weights_4[-1]])

    # остановка когда достигнута необходимая степень точности
    if np.linalg.norm(prev_W - curent_W) <= eps_1:
        break

    #print(f"Итерация: {i+1}")
    # print(f"Текущая точка {cur_W}| Следующая точка {next_W}")
    y_proba = sigmoid(X @ curent_W)
    y_class = np.where(y_proba >= 0.5, 1, 0)
    accuracy = (y_class == y).sum() / len(y)
    #accuracy = accuracy_score(y, y_class)
    #print(f"Logloss {logloss(y, y_proba)}")
    #print(f"Accuracy {accuracy}")
    #print("--------------------------------------------------------")
    results.loc[len(results.index)] = ['RMS-Prop', accuracy, i+1]

CPU times: user 389 ms, sys: 1.24 ms, total: 390 ms
Wall time: 410 ms


# **5. Повторите п. 3 для ускоренного по Нестерову метода адаптивной оценки моментов (Nesterov–accelerated Adaptive Moment Estimation, Nadam).**

In [ ]:
%%time
k = 200
lr = 0.01
eps_1 = 0.00001

# первоначальная точка
np.random.seed(43)
W = np.random.randn(X.shape[1])
weights_0, weights_1, weights_2, weights_3, weights_4, = [W[0]], [W[1]], [W[2]], [W[3]], [W[4]]

alphas = [0, 0, 0, 0, 0]
velocity = [0, 0, 0, 0, 0]
eps = 10e-7

b1 = 0.5
b2 = 0.9

for i in range(k):
    idx = np.random.choice(len(X), size=amount, replace=False)
    grad = gr_logloss(X[idx], W, y[idx])

    velocity[0] = b1 * velocity[0] + grad[0]
    velocity[1] = b1 * velocity[1] + grad[1]
    velocity[2] = b1 * velocity[2] + grad[2]
    velocity[3] = b1 * velocity[3] + grad[3]
    velocity[4] = b1 * velocity[4] + grad[4]

    alphas[0] = b2 * alphas[0] + (1 - b2) * grad[0] ** 2
    alphas[1] = b2 * alphas[1] + (1 - b2) * grad[1] ** 2
    alphas[2] = b2 * alphas[2] + (1 - b2) * grad[2] ** 2
    alphas[3] = b2 * alphas[3] + (1 - b2) * grad[3] ** 2
    alphas[4] = b2 * alphas[4] + (1 - b2) * grad[4] ** 2

    new_w_0 = weights_0[-1] - (lr * velocity[0]) / np.sqrt(alphas[0] + eps)
    new_w_1 = weights_1[-1] - (lr * velocity[1]) / np.sqrt(alphas[1] + eps)
    new_w_2 = weights_1[-1] - (lr * velocity[2]) / np.sqrt(alphas[2] + eps)
    new_w_3 = weights_1[-1] - (lr * velocity[3]) / np.sqrt(alphas[3] + eps)
    new_w_4 = weights_1[-1] - (lr * velocity[4]) / np.sqrt(alphas[4] + eps)

    weights_0.append(new_w_0)
    weights_1.append(new_w_1)
    weights_2.append(new_w_2)
    weights_3.append(new_w_3)
    weights_4.append(new_w_4)
    prev_W_1 = np.array([weights_0[-2], weights_1[-2], weights_2[-2], weights_3[-2], weights_4[-2]])
    curent_W_1 = np.array([weights_0[-1], weights_1[-1], weights_2[-1], weights_3[-1], weights_4[-1]])

    # остановка когда достигнута необходимая степень точности
    if np.linalg.norm(prev_W_1 - curent_W_1) <= eps_1:
        break

    #print(f"Итерация: {i+1}")
    # print(f"Текущая точка {cur_W}| Следующая точка {next_W}")
    y_proba = sigmoid(X @ curent_W_1)
    y_class = np.where(y_proba >= 0.5, 1, 0)
    accuracy = (y_class == y).sum() / len(y)
    #accuracy = accuracy_score(y, y_class)
    #print(f"Logloss {logloss(y, y_proba)}")
    #print(f"Accuracy {accuracy}")
    #print("--------------------------------------------------------")
    results.loc[len(results.index)] = ['Adam', accuracy, i+1]

CPU times: user 388 ms, sys: 1.7 ms, total: 390 ms
Wall time: 398 ms


In [ ]:
results.sort_values(by = ['Метрика'], ascending=False).head(20)

Метод  Метрика  Итерация
215        Mini-Batch     0.95        16
221        Mini-Batch     0.94        22
1    Gradient descent     0.94         2
216        Mini-Batch     0.94        17
217        Mini-Batch     0.94        18
218        Mini-Batch     0.94        19
219        Mini-Batch     0.94        20
210        Mini-Batch     0.93        11
229        Mini-Batch     0.93        30
228        Mini-Batch     0.93        29
227        Mini-Batch     0.93        28
226        Mini-Batch     0.93        27
225        Mini-Batch     0.93        26
224        Mini-Batch     0.93        25
223        Mini-Batch     0.93        24
222        Mini-Batch     0.93        23
220        Mini-Batch     0.93        21
214        Mini-Batch     0.93        15
213        Mini-Batch     0.93        14
212        Mini-Batch     0.93        13

In [ ]:
results.loc[results['Метод'] == 'Adam'].sort_values(by = ['Метрика'], ascending=False).head(10)

Метод  Метрика  Итерация
657  Adam     0.83        58
656  Adam     0.82        57
667  Adam     0.82        68
655  Adam     0.82        56
653  Adam     0.82        54
664  Adam     0.82        65
654  Adam     0.82        55
710  Adam     0.81       111
711  Adam     0.81       112
709  Adam     0.81       110

In [ ]:
results.loc[results['Метод'] == 'RMS-Prop'].sort_values(by = ['Метрика'], ascending=False).head(10)

Метод  Метрика  Итерация
456  RMS-Prop     0.91        57
455  RMS-Prop     0.91        56
454  RMS-Prop     0.91        55
463  RMS-Prop     0.90        64
451  RMS-Prop     0.90        52
464  RMS-Prop     0.90        65
471  RMS-Prop     0.90        72
470  RMS-Prop     0.90        71
469  RMS-Prop     0.90        70
468  RMS-Prop     0.90        69

# **6. Сравните значение метрик для реализованных методов оптимизации. Можно оформить в виде таблицы вида |метод|метрика|время работы| (время работы опционально). Напишите вывод.**

# **Выводы:**

**1. В целом все модели справелись с задачей более чем на 80%.**

**2. С точки зрения итераций, быстрее всех к максимальному качеству пришёл стандартный градиентный спуск, при этой по времени это самый долгий способ**

**3. Самый быстрый по времени является Adam, но он хуже всех справился с задачей с точки зрения качества**

**4. Самым сбалансированным при одинаковых условиях оказался метод "Mini-Batch"**